name: 'terra-pr-commenter'
description:
  'Utility action used for creating pull-request comments from the plan created
  via Terraform/Terragrunt'
author: 'deimantastumas'

# todo(): add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  # todo(): support passing a single/static terraform plan(s)
  tf-plan-lookup-dir:
    description: Directory where the lookup for TF plan JSON files will be done
    required: false
    default: '.'
  tf-plan-lookup-name:
    description:
      Goes along with 'tf-plan-lookup-dir' to specify which files should be
      looked
    required: false
    default: 'tfplan.json'
  github-token:
    description: GitHub Token
    required: false
    default: '${{ github.token }}'
  expand-comment:
    description: If true, expand the details comment by default
    required: false
    default: 'false'
  heading-plan-variable-name:
    description: Variable name from the plan that will be used for a heading.
    required: false
    default: ''
  comment-header:
    description:
      Header to use for the comment. Ignored if 'heading-plan-variable-name' is
      passed
    required: false
    default: 'Terraform Plan Changes'
  remove-previous-comments:
    description: Removes privious comments on the PR
    required: false
    default: 'false'
runs:
  using: node20
  main: dist/index.js
